// <auto-generated />
using System;
using System.Collections.Generic;
using HeatSphere.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeatSphere.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211162305_AddFluidsAndRefactorNotes")]
    partial class AddFluidsAndRefactorNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeatSphere.Domain.Entities.Fluid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fluids");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Air"
                        });
                });

            modelBuilder.Entity("HeatSphere.Domain.Entities.FluidPropertyPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Density")
                        .HasColumnType("double precision");

                    b.Property<double>("DynamicViscosity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FluidId")
                        .HasColumnType("uuid");

                    b.Property<double>("KinematicViscosity")
                        .HasColumnType("double precision");

                    b.Property<double>("Prandtl")
                        .HasColumnType("double precision");

                    b.Property<double>("SpecificHeatAtConstantPressure")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureK")
                        .HasColumnType("double precision");

                    b.Property<double>("ThermalConductivity")
                        .HasColumnType("double precision");

                    b.Property<double>("ThermalDiffusivity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FluidId");

                    b.ToTable("FluidPropertyPoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b750f72-b0e5-412a-b098-b4d7453fe3f9"),
                            Density = 3.5562,
                            DynamicViscosity = 7.1099999999999997E-06,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 1.9999999999999999E-06,
                            Prandtl = 0.78600000000000003,
                            SpecificHeatAtConstantPressure = 1032.0,
                            TemperatureK = 100.0,
                            ThermalConductivity = 0.0093399999999999993,
                            ThermalDiffusivity = 2.5399999999999998E-06
                        },
                        new
                        {
                            Id = new Guid("91c5054f-6eac-4ef0-b034-ec27d80b0588"),
                            Density = 2.3363999999999998,
                            DynamicViscosity = 1.0339999999999999E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 4.4259999999999996E-06,
                            Prandtl = 0.75800000000000001,
                            SpecificHeatAtConstantPressure = 1012.0,
                            TemperatureK = 150.0,
                            ThermalConductivity = 0.0138,
                            ThermalDiffusivity = 5.84E-06
                        },
                        new
                        {
                            Id = new Guid("52ec0c5c-2890-4e3e-8402-1abb588d1921"),
                            Density = 1.7458,
                            DynamicViscosity = 1.325E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 7.5900000000000002E-06,
                            Prandtl = 0.73699999999999999,
                            SpecificHeatAtConstantPressure = 1007.0,
                            TemperatureK = 200.0,
                            ThermalConductivity = 0.018100000000000002,
                            ThermalDiffusivity = 1.03E-05
                        },
                        new
                        {
                            Id = new Guid("4115e816-f515-43da-8732-4aaf730133ae"),
                            Density = 1.3947000000000001,
                            DynamicViscosity = 1.596E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 1.1440000000000001E-05,
                            Prandtl = 0.71999999999999997,
                            SpecificHeatAtConstantPressure = 1006.0,
                            TemperatureK = 250.0,
                            ThermalConductivity = 0.0223,
                            ThermalDiffusivity = 1.59E-05
                        },
                        new
                        {
                            Id = new Guid("29659671-b0c5-467c-9c93-14659cd3d0c8"),
                            Density = 1.1614,
                            DynamicViscosity = 1.8459999999999999E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 1.5889999999999999E-05,
                            Prandtl = 0.70699999999999996,
                            SpecificHeatAtConstantPressure = 1007.0,
                            TemperatureK = 300.0,
                            ThermalConductivity = 0.0263,
                            ThermalDiffusivity = 2.2500000000000001E-05
                        },
                        new
                        {
                            Id = new Guid("eee25fdd-1a04-473e-b7b3-7859c00cb85d"),
                            Density = 0.995,
                            DynamicViscosity = 2.0820000000000001E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 2.092E-05,
                            Prandtl = 0.69999999999999996,
                            SpecificHeatAtConstantPressure = 1009.0,
                            TemperatureK = 350.0,
                            ThermalConductivity = 0.029999999999999999,
                            ThermalDiffusivity = 2.9899999999999998E-05
                        },
                        new
                        {
                            Id = new Guid("4d11f64b-574a-4070-b069-790973bded83"),
                            Density = 0.87109999999999999,
                            DynamicViscosity = 2.3010000000000002E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 2.641E-05,
                            Prandtl = 0.68999999999999995,
                            SpecificHeatAtConstantPressure = 1014.0,
                            TemperatureK = 400.0,
                            ThermalConductivity = 0.033799999999999997,
                            ThermalDiffusivity = 3.8300000000000003E-05
                        },
                        new
                        {
                            Id = new Guid("09372026-1d92-4a22-a3d6-6cc4d645d872"),
                            Density = 0.77400000000000002,
                            DynamicViscosity = 2.5069999999999999E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 3.239E-05,
                            Prandtl = 0.68600000000000005,
                            SpecificHeatAtConstantPressure = 1021.0,
                            TemperatureK = 450.0,
                            ThermalConductivity = 0.0373,
                            ThermalDiffusivity = 4.7200000000000002E-05
                        },
                        new
                        {
                            Id = new Guid("17c2973c-396f-404f-a7fc-c8673c982172"),
                            Density = 0.69640000000000002,
                            DynamicViscosity = 2.7010000000000001E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 3.879E-05,
                            Prandtl = 0.68400000000000005,
                            SpecificHeatAtConstantPressure = 1030.0,
                            TemperatureK = 500.0,
                            ThermalConductivity = 0.0407,
                            ThermalDiffusivity = 5.6700000000000003E-05
                        },
                        new
                        {
                            Id = new Guid("478740e7-2ebf-49df-bc4a-7e91ee292308"),
                            Density = 0.63290000000000002,
                            DynamicViscosity = 2.8839999999999998E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 4.5569999999999999E-05,
                            Prandtl = 0.68300000000000005,
                            SpecificHeatAtConstantPressure = 1040.0,
                            TemperatureK = 550.0,
                            ThermalConductivity = 0.043900000000000002,
                            ThermalDiffusivity = 6.6699999999999995E-05
                        },
                        new
                        {
                            Id = new Guid("b049deee-a9d4-4430-9c10-1f4a21e51683"),
                            Density = 0.58040000000000003,
                            DynamicViscosity = 3.0580000000000002E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 5.2689999999999999E-05,
                            Prandtl = 0.68500000000000005,
                            SpecificHeatAtConstantPressure = 1051.0,
                            TemperatureK = 600.0,
                            ThermalConductivity = 0.046899999999999997,
                            ThermalDiffusivity = 7.6899999999999999E-05
                        },
                        new
                        {
                            Id = new Guid("bacd1486-a200-44c4-92a4-c62a39ef46f4"),
                            Density = 0.53559999999999997,
                            DynamicViscosity = 3.2249999999999998E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 6.0210000000000001E-05,
                            Prandtl = 0.68999999999999995,
                            SpecificHeatAtConstantPressure = 1063.0,
                            TemperatureK = 650.0,
                            ThermalConductivity = 0.049700000000000001,
                            ThermalDiffusivity = 8.7299999999999994E-05
                        },
                        new
                        {
                            Id = new Guid("cffdc9b8-1967-4dc2-9701-ac9f7b20ef2a"),
                            Density = 0.4975,
                            DynamicViscosity = 3.3880000000000001E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 6.8100000000000002E-05,
                            Prandtl = 0.69499999999999995,
                            SpecificHeatAtConstantPressure = 1075.0,
                            TemperatureK = 700.0,
                            ThermalConductivity = 0.052400000000000002,
                            ThermalDiffusivity = 9.7999999999999997E-05
                        },
                        new
                        {
                            Id = new Guid("ff63fe0f-c50d-4dd6-925d-6080cab7c4df"),
                            Density = 0.46429999999999999,
                            DynamicViscosity = 3.5460000000000003E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 7.6370000000000002E-05,
                            Prandtl = 0.70199999999999996,
                            SpecificHeatAtConstantPressure = 1087.0,
                            TemperatureK = 750.0,
                            ThermalConductivity = 0.054899999999999997,
                            ThermalDiffusivity = 0.00010900000000000001
                        },
                        new
                        {
                            Id = new Guid("de93d9d9-8e37-43f2-9fbd-1df18dd416f3"),
                            Density = 0.43540000000000001,
                            DynamicViscosity = 3.6980000000000002E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 8.4930000000000002E-05,
                            Prandtl = 0.70899999999999996,
                            SpecificHeatAtConstantPressure = 1099.0,
                            TemperatureK = 800.0,
                            ThermalConductivity = 0.057299999999999997,
                            ThermalDiffusivity = 0.00012
                        },
                        new
                        {
                            Id = new Guid("e11b90f4-0c47-43e0-bd97-9bd8c25f34c7"),
                            Density = 0.40970000000000001,
                            DynamicViscosity = 3.8430000000000003E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 9.3800000000000003E-05,
                            Prandtl = 0.71599999999999997,
                            SpecificHeatAtConstantPressure = 1110.0,
                            TemperatureK = 850.0,
                            ThermalConductivity = 0.0596,
                            ThermalDiffusivity = 0.00013100000000000001
                        },
                        new
                        {
                            Id = new Guid("275ad924-2d03-4789-b068-aaa1ea4065bb"),
                            Density = 0.38679999999999998,
                            DynamicViscosity = 3.981E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00010289999999999999,
                            Prandtl = 0.71999999999999997,
                            SpecificHeatAtConstantPressure = 1121.0,
                            TemperatureK = 900.0,
                            ThermalConductivity = 0.062,
                            ThermalDiffusivity = 0.00014300000000000001
                        },
                        new
                        {
                            Id = new Guid("9bf1219b-70fb-40bd-bd8e-9294fc078226"),
                            Density = 0.36659999999999998,
                            DynamicViscosity = 4.1130000000000001E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.0001122,
                            Prandtl = 0.72299999999999998,
                            SpecificHeatAtConstantPressure = 1131.0,
                            TemperatureK = 950.0,
                            ThermalConductivity = 0.064299999999999996,
                            ThermalDiffusivity = 0.000155
                        },
                        new
                        {
                            Id = new Guid("74e39d2e-9f35-4704-984f-00038d3ddb0d"),
                            Density = 0.34820000000000001,
                            DynamicViscosity = 4.244E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.0001219,
                            Prandtl = 0.72599999999999998,
                            SpecificHeatAtConstantPressure = 1141.0,
                            TemperatureK = 1000.0,
                            ThermalConductivity = 0.066699999999999995,
                            ThermalDiffusivity = 0.00016799999999999999
                        },
                        new
                        {
                            Id = new Guid("7bd2eaa0-93f0-4591-98cc-6614844f8462"),
                            Density = 0.31659999999999999,
                            DynamicViscosity = 4.49E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.0001418,
                            Prandtl = 0.72799999999999998,
                            SpecificHeatAtConstantPressure = 1159.0,
                            TemperatureK = 1100.0,
                            ThermalConductivity = 0.071499999999999994,
                            ThermalDiffusivity = 0.000195
                        },
                        new
                        {
                            Id = new Guid("70f8ccd8-55e3-4e7a-bd96-bd180a5a02c4"),
                            Density = 0.29020000000000001,
                            DynamicViscosity = 4.7299999999999998E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.0001629,
                            Prandtl = 0.72799999999999998,
                            SpecificHeatAtConstantPressure = 1175.0,
                            TemperatureK = 1200.0,
                            ThermalConductivity = 0.076300000000000007,
                            ThermalDiffusivity = 0.000224
                        },
                        new
                        {
                            Id = new Guid("e6eeaf04-da3d-4934-ae95-e99b51a2decb"),
                            Density = 0.26790000000000003,
                            DynamicViscosity = 4.9599999999999999E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.0001851,
                            Prandtl = 0.71899999999999997,
                            SpecificHeatAtConstantPressure = 1189.0,
                            TemperatureK = 1300.0,
                            ThermalConductivity = 0.082000000000000003,
                            ThermalDiffusivity = 0.00025700000000000001
                        },
                        new
                        {
                            Id = new Guid("cbc1d0fe-617b-45b2-823e-c36e63b3f4d9"),
                            Density = 0.24879999999999999,
                            DynamicViscosity = 5.3000000000000001E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.000213,
                            Prandtl = 0.70299999999999996,
                            SpecificHeatAtConstantPressure = 1207.0,
                            TemperatureK = 1400.0,
                            ThermalConductivity = 0.090999999999999998,
                            ThermalDiffusivity = 0.00030299999999999999
                        },
                        new
                        {
                            Id = new Guid("3cdf2121-09d1-4554-ab39-e6a5e2895c88"),
                            Density = 0.23219999999999999,
                            DynamicViscosity = 5.5699999999999999E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00024000000000000001,
                            Prandtl = 0.68500000000000005,
                            SpecificHeatAtConstantPressure = 1230.0,
                            TemperatureK = 1500.0,
                            ThermalConductivity = 0.10000000000000001,
                            ThermalDiffusivity = 0.00035
                        },
                        new
                        {
                            Id = new Guid("c1c937a7-83fe-4baa-988e-5a14d0703bc3"),
                            Density = 0.2177,
                            DynamicViscosity = 5.8400000000000003E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00026800000000000001,
                            Prandtl = 0.68799999999999994,
                            SpecificHeatAtConstantPressure = 1248.0,
                            TemperatureK = 1600.0,
                            ThermalConductivity = 0.106,
                            ThermalDiffusivity = 0.00038999999999999999
                        },
                        new
                        {
                            Id = new Guid("8b7b5992-72b0-45ad-9c9b-3e5b45b8bdbd"),
                            Density = 0.2049,
                            DynamicViscosity = 6.1099999999999994E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00029799999999999998,
                            Prandtl = 0.68500000000000005,
                            SpecificHeatAtConstantPressure = 1267.0,
                            TemperatureK = 1700.0,
                            ThermalConductivity = 0.113,
                            ThermalDiffusivity = 0.000435
                        },
                        new
                        {
                            Id = new Guid("5cb5ad5e-79eb-45f4-b25f-c93274ab427a"),
                            Density = 0.19350000000000001,
                            DynamicViscosity = 6.3700000000000003E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00032899999999999997,
                            Prandtl = 0.68300000000000005,
                            SpecificHeatAtConstantPressure = 1286.0,
                            TemperatureK = 1800.0,
                            ThermalConductivity = 0.12,
                            ThermalDiffusivity = 0.00048200000000000001
                        },
                        new
                        {
                            Id = new Guid("16a593ee-860f-4933-af6b-477a5ab928b6"),
                            Density = 0.18329999999999999,
                            DynamicViscosity = 6.6299999999999999E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00036200000000000002,
                            Prandtl = 0.67700000000000005,
                            SpecificHeatAtConstantPressure = 1307.0,
                            TemperatureK = 1900.0,
                            ThermalConductivity = 0.128,
                            ThermalDiffusivity = 0.00053399999999999997
                        },
                        new
                        {
                            Id = new Guid("863e4fc3-77c0-4ba5-b5c0-1b584e92b5dd"),
                            Density = 0.1741,
                            DynamicViscosity = 6.8899999999999994E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00039599999999999998,
                            Prandtl = 0.67200000000000004,
                            SpecificHeatAtConstantPressure = 1337.0,
                            TemperatureK = 2000.0,
                            ThermalConductivity = 0.13700000000000001,
                            ThermalDiffusivity = 0.00058900000000000001
                        },
                        new
                        {
                            Id = new Guid("80ad9b63-07cb-49f0-bd05-0083814f8b8c"),
                            Density = 0.1658,
                            DynamicViscosity = 7.1500000000000003E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00043100000000000001,
                            Prandtl = 0.66700000000000004,
                            SpecificHeatAtConstantPressure = 1372.0,
                            TemperatureK = 2100.0,
                            ThermalConductivity = 0.14699999999999999,
                            ThermalDiffusivity = 0.00064599999999999998
                        },
                        new
                        {
                            Id = new Guid("ab3d341f-1eff-4c04-85b2-640a2e9e8a22"),
                            Density = 0.15820000000000001,
                            DynamicViscosity = 7.3999999999999996E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00046799999999999999,
                            Prandtl = 0.65500000000000003,
                            SpecificHeatAtConstantPressure = 1417.0,
                            TemperatureK = 2200.0,
                            ThermalConductivity = 0.16,
                            ThermalDiffusivity = 0.00071400000000000001
                        },
                        new
                        {
                            Id = new Guid("70d0c3da-abe0-4f8d-ba90-9b0eb0ee40f8"),
                            Density = 0.15129999999999999,
                            DynamicViscosity = 7.6600000000000005E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00050600000000000005,
                            Prandtl = 0.64700000000000002,
                            SpecificHeatAtConstantPressure = 1478.0,
                            TemperatureK = 2300.0,
                            ThermalConductivity = 0.17499999999999999,
                            ThermalDiffusivity = 0.00078299999999999995
                        },
                        new
                        {
                            Id = new Guid("2889170b-aa4a-4c91-8b66-207bea20e1de"),
                            Density = 0.14480000000000001,
                            DynamicViscosity = 7.9200000000000001E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00054699999999999996,
                            Prandtl = 0.63,
                            SpecificHeatAtConstantPressure = 1558.0,
                            TemperatureK = 2400.0,
                            ThermalConductivity = 0.19600000000000001,
                            ThermalDiffusivity = 0.00086899999999999998
                        },
                        new
                        {
                            Id = new Guid("0cf0b9f4-44d0-42e2-bc16-70ea3b1fd925"),
                            Density = 0.1389,
                            DynamicViscosity = 8.1799999999999996E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00058900000000000001,
                            Prandtl = 0.61299999999999999,
                            SpecificHeatAtConstantPressure = 1665.0,
                            TemperatureK = 2500.0,
                            ThermalConductivity = 0.222,
                            ThermalDiffusivity = 0.00096000000000000002
                        },
                        new
                        {
                            Id = new Guid("562cea6e-fb3a-443f-82a2-e74bb326b036"),
                            Density = 0.1135,
                            DynamicViscosity = 9.5500000000000004E-05,
                            FluidId = new Guid("11111111-1111-1111-1111-111111111111"),
                            KinematicViscosity = 0.00084099999999999995,
                            Prandtl = 0.53600000000000003,
                            SpecificHeatAtConstantPressure = 2726.0,
                            TemperatureK = 3000.0,
                            ThermalConductivity = 0.48599999999999999,
                            ThermalDiffusivity = 0.00157
                        });
                });

            modelBuilder.Entity("HeatSphere.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BriefDefinition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("Id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("HeatSphere.Domain.Entities.FluidPropertyPoint", b =>
                {
                    b.HasOne("HeatSphere.Domain.Entities.Fluid", null)
                        .WithMany("Properties")
                        .HasForeignKey("FluidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeatSphere.Domain.Entities.Fluid", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
